// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sudoku.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sudoku_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sudoku_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sudoku_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sudoku_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sudoku_2eproto;
namespace sudoku {
class Sudoku;
struct SudokuDefaultTypeInternal;
extern SudokuDefaultTypeInternal _Sudoku_default_instance_;
}  // namespace sudoku
PROTOBUF_NAMESPACE_OPEN
template<> ::sudoku::Sudoku* Arena::CreateMaybeMessage<::sudoku::Sudoku>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sudoku {

// ===================================================================

class Sudoku final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sudoku.Sudoku) */ {
 public:
  inline Sudoku() : Sudoku(nullptr) {}
  ~Sudoku() override;
  explicit PROTOBUF_CONSTEXPR Sudoku(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Sudoku(const Sudoku& from);
  Sudoku(Sudoku&& from) noexcept
    : Sudoku() {
    *this = ::std::move(from);
  }

  inline Sudoku& operator=(const Sudoku& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sudoku& operator=(Sudoku&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Sudoku& default_instance() {
    return *internal_default_instance();
  }
  static inline const Sudoku* internal_default_instance() {
    return reinterpret_cast<const Sudoku*>(
               &_Sudoku_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Sudoku& a, Sudoku& b) {
    a.Swap(&b);
  }
  inline void Swap(Sudoku* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sudoku* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Sudoku* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Sudoku>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Sudoku& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Sudoku& from) {
    Sudoku::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sudoku* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sudoku.Sudoku";
  }
  protected:
  explicit Sudoku(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValuesFieldNumber = 2,
    kNbEmptyFieldNumber = 1,
    kScoreFieldNumber = 3,
    kLevelFieldNumber = 4,
  };
  // repeated int32 values = 2;
  int values_size() const;
  private:
  int _internal_values_size() const;
  public:
  void clear_values();
  private:
  int32_t _internal_values(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_values() const;
  void _internal_add_values(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_values();
  public:
  int32_t values(int index) const;
  void set_values(int index, int32_t value);
  void add_values(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      values() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_values();

  // required int32 nbEmpty = 1;
  bool has_nbempty() const;
  private:
  bool _internal_has_nbempty() const;
  public:
  void clear_nbempty();
  int32_t nbempty() const;
  void set_nbempty(int32_t value);
  private:
  int32_t _internal_nbempty() const;
  void _internal_set_nbempty(int32_t value);
  public:

  // required int32 score = 3;
  bool has_score() const;
  private:
  bool _internal_has_score() const;
  public:
  void clear_score();
  int32_t score() const;
  void set_score(int32_t value);
  private:
  int32_t _internal_score() const;
  void _internal_set_score(int32_t value);
  public:

  // required int32 level = 4;
  bool has_level() const;
  private:
  bool _internal_has_level() const;
  public:
  void clear_level();
  int32_t level() const;
  void set_level(int32_t value);
  private:
  int32_t _internal_level() const;
  void _internal_set_level(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:sudoku.Sudoku)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > values_;
    int32_t nbempty_;
    int32_t score_;
    int32_t level_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sudoku_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Sudoku

// required int32 nbEmpty = 1;
inline bool Sudoku::_internal_has_nbempty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Sudoku::has_nbempty() const {
  return _internal_has_nbempty();
}
inline void Sudoku::clear_nbempty() {
  _impl_.nbempty_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline int32_t Sudoku::_internal_nbempty() const {
  return _impl_.nbempty_;
}
inline int32_t Sudoku::nbempty() const {
  // @@protoc_insertion_point(field_get:sudoku.Sudoku.nbEmpty)
  return _internal_nbempty();
}
inline void Sudoku::_internal_set_nbempty(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.nbempty_ = value;
}
inline void Sudoku::set_nbempty(int32_t value) {
  _internal_set_nbempty(value);
  // @@protoc_insertion_point(field_set:sudoku.Sudoku.nbEmpty)
}

// repeated int32 values = 2;
inline int Sudoku::_internal_values_size() const {
  return _impl_.values_.size();
}
inline int Sudoku::values_size() const {
  return _internal_values_size();
}
inline void Sudoku::clear_values() {
  _impl_.values_.Clear();
}
inline int32_t Sudoku::_internal_values(int index) const {
  return _impl_.values_.Get(index);
}
inline int32_t Sudoku::values(int index) const {
  // @@protoc_insertion_point(field_get:sudoku.Sudoku.values)
  return _internal_values(index);
}
inline void Sudoku::set_values(int index, int32_t value) {
  _impl_.values_.Set(index, value);
  // @@protoc_insertion_point(field_set:sudoku.Sudoku.values)
}
inline void Sudoku::_internal_add_values(int32_t value) {
  _impl_.values_.Add(value);
}
inline void Sudoku::add_values(int32_t value) {
  _internal_add_values(value);
  // @@protoc_insertion_point(field_add:sudoku.Sudoku.values)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Sudoku::_internal_values() const {
  return _impl_.values_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Sudoku::values() const {
  // @@protoc_insertion_point(field_list:sudoku.Sudoku.values)
  return _internal_values();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Sudoku::_internal_mutable_values() {
  return &_impl_.values_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Sudoku::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:sudoku.Sudoku.values)
  return _internal_mutable_values();
}

// required int32 score = 3;
inline bool Sudoku::_internal_has_score() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Sudoku::has_score() const {
  return _internal_has_score();
}
inline void Sudoku::clear_score() {
  _impl_.score_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t Sudoku::_internal_score() const {
  return _impl_.score_;
}
inline int32_t Sudoku::score() const {
  // @@protoc_insertion_point(field_get:sudoku.Sudoku.score)
  return _internal_score();
}
inline void Sudoku::_internal_set_score(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.score_ = value;
}
inline void Sudoku::set_score(int32_t value) {
  _internal_set_score(value);
  // @@protoc_insertion_point(field_set:sudoku.Sudoku.score)
}

// required int32 level = 4;
inline bool Sudoku::_internal_has_level() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Sudoku::has_level() const {
  return _internal_has_level();
}
inline void Sudoku::clear_level() {
  _impl_.level_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline int32_t Sudoku::_internal_level() const {
  return _impl_.level_;
}
inline int32_t Sudoku::level() const {
  // @@protoc_insertion_point(field_get:sudoku.Sudoku.level)
  return _internal_level();
}
inline void Sudoku::_internal_set_level(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.level_ = value;
}
inline void Sudoku::set_level(int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:sudoku.Sudoku.level)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace sudoku

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sudoku_2eproto
