// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sudoku.proto

#include "sudoku.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sudoku {
PROTOBUF_CONSTEXPR Sudoku::Sudoku(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.values_)*/{}
  , /*decltype(_impl_.nbempty_)*/0
  , /*decltype(_impl_.score_)*/0
  , /*decltype(_impl_.level_)*/0} {}
struct SudokuDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SudokuDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SudokuDefaultTypeInternal() {}
  union {
    Sudoku _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SudokuDefaultTypeInternal _Sudoku_default_instance_;
}  // namespace sudoku
static ::_pb::Metadata file_level_metadata_sudoku_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sudoku_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sudoku_2eproto = nullptr;

const uint32_t TableStruct_sudoku_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::sudoku::Sudoku, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::sudoku::Sudoku, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sudoku::Sudoku, _impl_.nbempty_),
  PROTOBUF_FIELD_OFFSET(::sudoku::Sudoku, _impl_.values_),
  PROTOBUF_FIELD_OFFSET(::sudoku::Sudoku, _impl_.score_),
  PROTOBUF_FIELD_OFFSET(::sudoku::Sudoku, _impl_.level_),
  0,
  ~0u,
  1,
  2,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, -1, sizeof(::sudoku::Sudoku)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sudoku::_Sudoku_default_instance_._instance,
};

const char descriptor_table_protodef_sudoku_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014sudoku.proto\022\006sudoku\"G\n\006Sudoku\022\017\n\007nbEm"
  "pty\030\001 \002(\005\022\016\n\006values\030\002 \003(\005\022\r\n\005score\030\003 \002(\005"
  "\022\r\n\005level\030\004 \002(\005"
  ;
static ::_pbi::once_flag descriptor_table_sudoku_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sudoku_2eproto = {
    false, false, 95, descriptor_table_protodef_sudoku_2eproto,
    "sudoku.proto",
    &descriptor_table_sudoku_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_sudoku_2eproto::offsets,
    file_level_metadata_sudoku_2eproto, file_level_enum_descriptors_sudoku_2eproto,
    file_level_service_descriptors_sudoku_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sudoku_2eproto_getter() {
  return &descriptor_table_sudoku_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sudoku_2eproto(&descriptor_table_sudoku_2eproto);
namespace sudoku {

// ===================================================================

class Sudoku::_Internal {
 public:
  using HasBits = decltype(std::declval<Sudoku>()._impl_._has_bits_);
  static void set_has_nbempty(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_score(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_level(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

Sudoku::Sudoku(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sudoku.Sudoku)
}
Sudoku::Sudoku(const Sudoku& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Sudoku* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.values_){from._impl_.values_}
    , decltype(_impl_.nbempty_){}
    , decltype(_impl_.score_){}
    , decltype(_impl_.level_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.nbempty_, &from._impl_.nbempty_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.level_) -
    reinterpret_cast<char*>(&_impl_.nbempty_)) + sizeof(_impl_.level_));
  // @@protoc_insertion_point(copy_constructor:sudoku.Sudoku)
}

inline void Sudoku::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.values_){arena}
    , decltype(_impl_.nbempty_){0}
    , decltype(_impl_.score_){0}
    , decltype(_impl_.level_){0}
  };
}

Sudoku::~Sudoku() {
  // @@protoc_insertion_point(destructor:sudoku.Sudoku)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Sudoku::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.values_.~RepeatedField();
}

void Sudoku::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Sudoku::Clear() {
// @@protoc_insertion_point(message_clear_start:sudoku.Sudoku)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.values_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.nbempty_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.level_) -
        reinterpret_cast<char*>(&_impl_.nbempty_)) + sizeof(_impl_.level_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Sudoku::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required int32 nbEmpty = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_nbempty(&has_bits);
          _impl_.nbempty_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 values = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_values(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<16>(ptr));
        } else if (static_cast<uint8_t>(tag) == 18) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_values(), ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required int32 score = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_score(&has_bits);
          _impl_.score_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required int32 level = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_level(&has_bits);
          _impl_.level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Sudoku::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sudoku.Sudoku)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required int32 nbEmpty = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_nbempty(), target);
  }

  // repeated int32 values = 2;
  for (int i = 0, n = this->_internal_values_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_values(i), target);
  }

  // required int32 score = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_score(), target);
  }

  // required int32 level = 4;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_level(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sudoku.Sudoku)
  return target;
}

size_t Sudoku::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:sudoku.Sudoku)
  size_t total_size = 0;

  if (_internal_has_nbempty()) {
    // required int32 nbEmpty = 1;
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_nbempty());
  }

  if (_internal_has_score()) {
    // required int32 score = 3;
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_score());
  }

  if (_internal_has_level()) {
    // required int32 level = 4;
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_level());
  }

  return total_size;
}
size_t Sudoku::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sudoku.Sudoku)
  size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required int32 nbEmpty = 1;
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_nbempty());

    // required int32 score = 3;
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_score());

    // required int32 level = 4;
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_level());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 values = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.values_);
    total_size += 1 *
                  ::_pbi::FromIntSize(this->_internal_values_size());
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Sudoku::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Sudoku::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Sudoku::GetClassData() const { return &_class_data_; }


void Sudoku::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Sudoku*>(&to_msg);
  auto& from = static_cast<const Sudoku&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sudoku.Sudoku)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.values_.MergeFrom(from._impl_.values_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.nbempty_ = from._impl_.nbempty_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.score_ = from._impl_.score_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.level_ = from._impl_.level_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Sudoku::CopyFrom(const Sudoku& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sudoku.Sudoku)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sudoku::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void Sudoku::InternalSwap(Sudoku* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.values_.InternalSwap(&other->_impl_.values_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sudoku, _impl_.level_)
      + sizeof(Sudoku::_impl_.level_)
      - PROTOBUF_FIELD_OFFSET(Sudoku, _impl_.nbempty_)>(
          reinterpret_cast<char*>(&_impl_.nbempty_),
          reinterpret_cast<char*>(&other->_impl_.nbempty_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Sudoku::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sudoku_2eproto_getter, &descriptor_table_sudoku_2eproto_once,
      file_level_metadata_sudoku_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace sudoku
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sudoku::Sudoku*
Arena::CreateMaybeMessage< ::sudoku::Sudoku >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sudoku::Sudoku >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
